### ISSUE TITLE
Adapter la topbarre aux grandes résolutions

### ISSUE THREAD

**Issue by ahirel** [AmauryCarrade/Webnel-Admin#2]
Sur les grandes résolutions d'écran, la topbarre ne s'adapte pas et reste petite et centrée au milieu.

**Comment by AmauryCarrade** [comment]
...Pourquoi fermer soudainement plus de quatre ans après ? Une raison particulière ?

**Comment by ahirel** [comment]
Ça me stressait d'avoir des tickets non fermés dans ma liste d'issues :)
